#!/bin/bash
LONG=port:,origin:,name:,username:,keyfile:
SHORT=p:,o:,n:,u:,i:
OPTS=$(getopt --alternative --options $SHORT --longoptions $LONG -- "$@") 

eval set -- "$OPTS"

while :
do
  case "$1" in
	-p | --port)       PORT="$2"       ; shift 2  ;;
    -o | --origin)     ORIGIN="$2"     ; shift 2  ;;
	-n | --name)       NAME="$2"       ; shift 2  ;;
	-u | --username)   SERVERUSER="$2"    ; shift 2  ;;
	-i | --keyfile)    KEYFILE="$2"    ; shift 2  ;;
	--) shift; break ;;
	*) echo "Unexpected option: $1 - this should not happen."
       usage ;;
  esac
done

REPLICA_SERVERS=("proj4-repl1.5700.network" "proj4-repl2.5700.network" "proj4-repl3.5700.network" "proj4-repl4.5700.network" "proj4-repl5.5700.network" "proj4-repl6.5700.network" "proj4-repl7.5700.network")
for repl in "${REPLICA_SERVERS[@]}"
do
	echo "Deploying to $repl"
	ssh -i $KEYFILE $SERVERUSER@$repl "rm -rf  .cache .config .local .bash_history" 
	scp -i $KEYFILE -r httpserver/httpserver $SERVERUSER@$repl: 
	rsync -e "ssh -i $KEYFILE" -a --delete httpserver/disk/ $SERVERUSER@$repl:disk/  
done

dns_server="proj4-dns.5700.network"
echo "Deploying to $dns_server"
scp dnsserver/dnsserver dnsserver/GeoLite2-City.mmdb $SERVERUSER@$dns_server:
ssh -i $KEYFILE $SERVERUSER@$dns_server  "pip3 install -U geoip2 && chmod u+x dnsserver"
